
### // Test API
POST https://httpbin.org/post

### // V1 home
GET http://localhost:8889/api/scread/v1

GET http://localhost:8889/api/scread/

### // Get DEG list by two comparison data IDs, cell type, comparison type
GET http://localhost:8889/api/scread/de/AD00105?second_id=AD00103&ct=ast&type=cts

### // Get DEG list comparison type
GET http://localhost:8889/api/scread/de/AD00103/meta


### // Get iris3 table info by data id
GET http://localhost:8889/api/scread/regulon/AD00102


### // Get all dataset info
GET http://localhost:8889/api/scread/dataset

### // Get dataset info by ID
GET http://localhost:8889/api/scread/dataset/AD00102

### // Get dataset info by ID
GET http://localhost:8889/api/scread/dataset/AD00105

### // Get all UMAP info by ID
GET http://localhost:8889/api/scread/dimension/AD00101/type/all


### // Get subcluster UMAP info by ID
GET http://localhost:8889/api/scread/dimension/AD00103/type/subcluster

### // Get all cell types by ID
GET http://localhost:8889/api/scread/celltype/AD00103/


### // 
GET http://localhost:8889/api/scread/de/AD00103?second_id=0&ct=Astrocytes&type=subcluster


### // 
GET http://localhost:8889/api/scread/de/AD00103?second_id=AD00103&ct=Endothelial%20cells&type=cell_type_specific


### // 
GET http://localhost:8889/api/scread/de/AD00718?second_id=0&ct=Excitatory%20neurons&type=subcluster


### // 
GET http://localhost:8889/api/scread/expression_genes/AD00602

### // 
POST http://localhost:8889/api/scread/upload


### // 
GET http://localhost:8889/api/scread/expression/Lrrtm4/id/AD00602

### // 
GET http://localhost:8889/api/scread/de/gene/malat1

### // 
GET http://localhost:8889/api/scread/de/type